#!/usr/bin/env python3
"""
Subset the Aptos headings font out of the local Microsoft Office install and embed it as
data URIs in site/src/fonts.css.

    python build_fonts.py

Why embed rather than link the .woff2 files: Observable Framework bundles the stylesheet named
in observablehq.config.js through esbuild with bundle:true, and esbuild has no loader for
.woff2 and no way to add one from a Framework project — a plain url("./fonts/x.woff2") fails
the build outright. Data URIs pass through esbuild untouched, land in the single cached
stylesheet rather than in every page's <head>, and cost no extra request.

Aptos is not on Google Fonts and is never registered with the OS even where Office is
installed (the files live inside the app bundle), so self-hosting is the only way headings
render as Aptos for anyone but the author.

Needs fonttools + brotli, which live in the project venv alongside the data-pipeline deps:

    source .venv/bin/activate && python build_fonts.py
"""
import base64
import subprocess
import sys
import tempfile
from pathlib import Path

DFONTS = Path("/Applications/Microsoft Word.app/Contents/Resources/DFonts")
OUT = Path("site/src/fonts.css")

# Only the weights headings actually ask for: h2 is 600, every other heading level is 700.
WEIGHTS = [("Aptos-SemiBold", 600), ("Aptos-Bold", 700)]

# Latin-1 plus the arrows, dashes and diamond the headings and axis labels use. Keeps each
# weight near 18kB instead of the full 216kB face.
UNICODES = (
    "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,"
    "U+2074,U+20AC,U+2122,U+2190-2199,U+2212,U+2215,U+25CA,U+FEFF,U+FFFD"
)


def check_deps() -> None:
    try:
        import brotli  # noqa: F401  (fontTools shells out to it for woff2)
        import fontTools  # noqa: F401
    except ModuleNotFoundError as e:
        sys.exit(
            f"{e.name} is missing. Run it from the project venv:\n"
            "    source .venv/bin/activate && pip install fonttools brotli"
        )


def subset(src: Path, dest: Path) -> None:
    subprocess.run(
        [sys.executable, "-m", "fontTools.subset", str(src),
         f"--output-file={dest}", "--flavor=woff2", "--layout-features=kern,liga,calt",
         f"--unicodes={UNICODES}", "--desubroutinize"],
        check=True, capture_output=True,
    )


def main() -> None:
    check_deps()
    if not DFONTS.is_dir():
        sys.exit(f"{DFONTS} not found — install Microsoft Office or point DFONTS at the Aptos files")
    rules = []
    with tempfile.TemporaryDirectory() as tmp:
        for name, weight in WEIGHTS:
            src = DFONTS / f"{name}.ttf"
            if not src.exists():
                sys.exit(f"missing {src}")
            woff2 = Path(tmp) / f"{name}.woff2"
            subset(src, woff2)
            data = woff2.read_bytes()
            b64 = base64.b64encode(data).decode("ascii")
            print(f"{name}: {src.stat().st_size / 1024:.0f}kB ttf -> {len(data) / 1024:.1f}kB woff2")
            rules.append(
                '@font-face {\n'
                '  font-family: "Aptos";\n'
                f'  src: url("data:font/woff2;base64,{b64}") format("woff2");\n'
                f'  font-weight: {weight};\n'
                '  font-style: normal;\n'
                '  font-display: swap;\n'
                '}'
            )
    OUT.write_text(
        "/* Generated by build_fonts.py — do not edit. */\n" + "\n".join(rules) + "\n"
    )
    print(f"{OUT} written ({OUT.stat().st_size / 1024:.0f}kB)")


if __name__ == "__main__":
    main()
