#!/usr/bin/env python3
"""
Download club crests from DRIBL (ocean.dribl.com, not Cloudflare-protected) into the site.

    python download_crests.py        # reads output/dribl_raw_2026_v2.json ladders -> site/src/assets/crests/<code>.png

Writes site/src/data/clubs.csv (club, code, crest path, source url). Colours are added later by
build_site_data.py from the member profiles.
"""
import csv
import json
import re
from pathlib import Path

import requests

RAW = Path("output/dribl_raw_2026_v2.json")
CRESTS = Path("site/src/assets/crests")
CLUBS_CSV = Path("site/src/data/clubs.csv")
CRESTS_JS = Path("site/src/components/crests.js")


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def main():
    raw = json.load(open(RAW))
    clubs = {}
    for entries in raw["ladders"].values():
        for e in entries:
            name = e.get("club_name")
            if name and name not in clubs:
                clubs[name] = {"club": name, "code": e.get("club_code") or slug(name)[:6].upper(), "logo_url": e.get("club_logo")}
    CRESTS.mkdir(parents=True, exist_ok=True)
    rows = []
    for name, c in sorted(clubs.items()):
        key = slug(name)
        path = CRESTS / f"{key}.png"
        ok = False
        if c["logo_url"]:
            if not path.exists():
                r = requests.get(c["logo_url"], timeout=30, headers={"User-Agent": "Mozilla/5.0"})
                if r.ok and r.headers.get("content-type", "").startswith("image/"):
                    path.write_bytes(r.content)
            ok = path.exists() and path.stat().st_size > 500
        rows.append({"club": name, "code": c["code"], "slug": key, "crest": f"./assets/crests/{key}.png" if ok else "", "logo_url": c["logo_url"] or ""})
        print(f"{'ok ' if ok else 'MISSING'} {name} -> {path.name if ok else '-'}")
    CLUBS_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(CLUBS_CSV, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["club", "code", "slug", "crest", "logo_url"])
        w.writeheader()
        w.writerows(rows)
    # Framework only serves/copies files referenced by a literal FileAttachment path, so generate one per crest.
    lines = ["// Generated by download_crests.py — do not edit.", 'import {FileAttachment} from "observablehq:stdlib";', "", "export const crestHref = {"]
    for r in rows:
        if r["crest"]:
            lines.append(f'  "{r["slug"]}": FileAttachment("../assets/crests/{r["slug"]}.png").href,')
    lines += ["};", ""]
    CRESTS_JS.write_text("\n".join(lines))
    print(f"{sum(1 for r in rows if r['crest'])}/{len(rows)} crests saved; {CLUBS_CSV} and {CRESTS_JS} written")


if __name__ == "__main__":
    main()
